name: Frontend Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - "starter/frontend/**"

  pull_request:
    branches:
      - master
    paths:
      - "starter/frontend/**"

  workflow_dispatch:
